export const SIGNUP_START='SIGNUP_START'
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_ERROR='SIGNUP_ERROR'


export const LOGIN_START='LOGIN_START'
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const LOGIN_ERROR='LOGIN_ERROR'

export const LOGOUT_START='LOGOUT_START'
export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
export const LOGOUT_ERROR='LOGOUT_ERROR'

export const SET_USER='SET_USER'

export const GOOGLE_SIGNIN_START='GOOGLE_SIGNIN_START'
export const GOOGLE_SIGNIN_SUCCESS='GOOGLE_SIGNIN_SUCCESS'
export const GOOGLE_SIGNIN_ERROR='GOOGLE_SIGNIN_ERROR'
